//go:build windows

package webview2

type COREWEBVIEW2_POINTER_EVENT_KIND uint32

const (
	COREWEBVIEW2_POINTER_EVENT_KIND_ACTIVATE = 0x024B
	COREWEBVIEW2_POINTER_EVENT_KIND_DOWN     = 0x0246
	COREWEBVIEW2_POINTER_EVENT_KIND_ENTER    = 0x0249
	COREWEBVIEW2_POINTER_EVENT_KIND_LEAVE    = 0x024A
	COREWEBVIEW2_POINTER_EVENT_KIND_UP       = 0x0247
	COREWEBVIEW2_POINTER_EVENT_KIND_UPDATE   = 0x0245
)
