//go:build windows

package webview2

type COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS uint32

const (
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_NONE          = 0x0
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_LEFT_BUTTON   = 0x0001
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_RIGHT_BUTTON  = 0x0002
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_SHIFT         = 0x0004
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_CONTROL       = 0x0008
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_MIDDLE_BUTTON = 0x0010
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_X_BUTTON1     = 0x0020
	COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_X_BUTTON2     = 0x0040
)
