//go:build windows

package webview2

type COREWEBVIEW2_MOUSE_EVENT_KIND uint32

const (
	COREWEBVIEW2_MOUSE_EVENT_KIND_HORIZONTAL_WHEEL             = 0x020E
	COREWEBVIEW2_MOUSE_EVENT_KIND_LEFT_BUTTON_DOUBLE_CLICK     = 0x0203
	COREWEBVIEW2_MOUSE_EVENT_KIND_LEFT_BUTTON_DOWN             = 0x0201
	COREWEBVIEW2_MOUSE_EVENT_KIND_LEFT_BUTTON_UP               = 0x0202
	COREWEBVIEW2_MOUSE_EVENT_KIND_LEAVE                        = 0x02A3
	COREWEBVIEW2_MOUSE_EVENT_KIND_MIDDLE_BUTTON_DOUBLE_CLICK   = 0x0209
	COREWEBVIEW2_MOUSE_EVENT_KIND_MIDDLE_BUTTON_DOWN           = 0x0207
	COREWEBVIEW2_MOUSE_EVENT_KIND_MIDDLE_BUTTON_UP             = 0x0208
	COREWEBVIEW2_MOUSE_EVENT_KIND_MOVE                         = 0x0200
	COREWEBVIEW2_MOUSE_EVENT_KIND_RIGHT_BUTTON_DOUBLE_CLICK    = 0x0206
	COREWEBVIEW2_MOUSE_EVENT_KIND_RIGHT_BUTTON_DOWN            = 0x0204
	COREWEBVIEW2_MOUSE_EVENT_KIND_RIGHT_BUTTON_UP              = 0x0205
	COREWEBVIEW2_MOUSE_EVENT_KIND_WHEEL                        = 0x020A
	COREWEBVIEW2_MOUSE_EVENT_KIND_X_BUTTON_DOUBLE_CLICK        = 0x020D
	COREWEBVIEW2_MOUSE_EVENT_KIND_X_BUTTON_DOWN                = 0x020B
	COREWEBVIEW2_MOUSE_EVENT_KIND_X_BUTTON_UP                  = 0x020C
	COREWEBVIEW2_MOUSE_EVENT_KIND_NON_CLIENT_RIGHT_BUTTON_DOWN = 0x00A4
	COREWEBVIEW2_MOUSE_EVENT_KIND_NON_CLIENT_RIGHT_BUTTON_UP   = 0x00A5
)
