//go:build windows

package webview2

type _ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandlerVtbl struct {
	_IUnknownVtbl
	Invoke ComProc
}

type ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler struct {
	vtbl *_ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandlerVtbl
	impl _ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandlerImpl
}

func (i *ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler) AddRef() uintptr {
	return i.AddRef()
}
func _ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandlerIUnknownQueryInterface(this *ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler, refiid, object uintptr) uintptr {
	return this.impl.QueryInterface(refiid, object)
}

func _ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandlerIUnknownAddRef(this *ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler) uintptr {
	return this.impl.AddRef()
}

func _ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandlerIUnknownRelease(this *ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler) uintptr {
	return this.impl.Release()
}

func _ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandlerInvoke(this *ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler, errorCode uintptr, createdEnvironment *ICoreWebView2Environment) uintptr {
	return this.impl.CreateCoreWebView2EnvironmentCompleted(errorCode, createdEnvironment)
}

type _ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandlerImpl interface {
	_IUnknownImpl
	CreateCoreWebView2EnvironmentCompleted(errorCode uintptr, createdEnvironment *ICoreWebView2Environment) uintptr
}

var _ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandlerFn = _ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandlerVtbl{
	_IUnknownVtbl{
		NewComProc(_ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandlerIUnknownQueryInterface),
		NewComProc(_ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandlerIUnknownAddRef),
		NewComProc(_ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandlerIUnknownRelease),
	},
	NewComProc(_ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandlerInvoke),
}

func NewICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler(impl _ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandlerImpl) *ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler {
	return &ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler{
		vtbl: &_ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandlerFn,
		impl: impl,
	}
}
